#!/bin/sh

##
# apt-install-favorites
#
# Use the `apt` command to install our favorite packages
# for Debian, Ubuntu, Mint, etc.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/apt-install-favorites
# * Version: 1.2.0
# * Created: 2020-06-19T06:15:16Z
# * Updated: 2025-11-27T13:35:03Z
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

##
# Bootstrapping
##

# Setup
apt -y install ansible

# Development
apt -y install autoconf
apt -y install automake
apt -y install bison
apt -y install build-essential
apt -y install cmake
apt -y install flex
apt -y install apt-transport-https
apt -y install build-essential
apt -y install ca-certificates
apt -y install curl
apt -y install gcc
apt -y install gdb
apt -y install gcc
apt -y install git
apt -y install git-core
apt -y install gnupg-agent
apt -y install make
apt -y install openssl
apt -y install patch
apt -y install pkg-config
apt -y install software-properties-common
apt -y install xfsprogs

# Libs
apt -y install ssl-cert
apt -y install libffi-dev
apt -y install libgeos-dev
apt -y install libssl-dev
apt -y install libv8-dev
apt -y install libxml2-dev
apt -y install libxslt-dev

# Fetching
apt -y install curl
apt -y install wget
apt -y install jq

# Editing
apt -y install emacs
apt -y install nano
apt -y install vim

# Operating
apt -y install daemon

##
# Docker
##

# Add Docker's official GPG key:
apt update
apt install ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

apt update
apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

##
# Programming
##

# Compiler-related
apt -y install gcc

# Java-related
apt -y install default-jre
apt -y install default-jdk

# Node-related
apt -y install nodejs
apt -y install npm

# Perl-related
apt -y install perl

# Python-related
apt -y install python3
apt -y install python3-dev
apt -y install python3-geopandas
apt -y install python3-numpy
apt -y install python3-pip

# Ruby-related
apt -y install ruby
apt -y install ruby-dev

# Rust-related
apt -y install cargo

# NGINX webserver-related
apt -y install nginx
apt -y install geoip-bin nginx-module-geoip
apt -y install libgd-dev nginx-module-image-filter
apt -y install libnode-dev nginx-module-njs
apt -y install perl nginx-module-perl
apt -y install libxslt-dev nginx-module-xslt

# Utiltiies
apt -y install ack-grep
apt -y install atop
apt -y install elinks
apt -y install fd-find
apt -y install gnupg
apt -y install gnupg-agent
apt -y install htop
apt -y install jq
apt -y install lynx
apt -y install most
apt -y install mutt
apt -y install pcregrep
apt -y install readline-common
apt -y install ripgrep
apt -y install rsync
apt -y install screen
apt -y install shellcheck
apt -y install tmux
apt -y install traceroute
apt -y install unrar-free
apt -y install unzip
apt -y install uuid
apt -y install uuid-dev
apt -y install uuid-runtime

# Services
apt -y install monit

# Apache webserver related
apt -y install apache2
apt -y install apache2-doc
apt -y install apache2-utils
apt -y install libapr1
apt -y install libaprutil1
apt -y install libpq5
apt -y install libaprutil1-dev
apt -y install libapr1-dev
apt -y install libexpat1
apt -y install ssl-cert

# NGINX webserver related
apt -y install nginx

# Z shell
apt -y install zsh
apt -y install zsh-doc
